# SPDX-FileCopyrightText: 2026 Frankenstein contributors
# SPDX-License-Identifier: MIT

source /etc/makepkg.conf

BUILDDIR="$startdir/build"
SRCDEST="$startdir/sources"
PKGDEST="$startdir/packages"
SRCPKGDEST="$startdir/source-packages"
LOGDEST="$startdir/logs"
