[General]
showlogo=hidden
showClock=true
logo=/usr/share/sddm/themes/omarchy-desktop-manager/default-logo.svg
type=image
color=#21183c
fontSize=10
background=/usr/share/sddm/themes/omarchy-desktop-manager/background
needsFullUserModel=false
