[Theme]
Current=omarchy-desktop-manager

[Users]
RememberLastUser=true
RememberLastSession=true

[Autologin]
User=
Session=
Relogin=false
# SPDX-FileCopyrightText: 2026 Frankenstein contributors
# SPDX-License-Identifier: MIT
