# SPDX-FileCopyrightText: 2026 Frankenstein contributors
# SPDX-License-Identifier: MIT

[Theme]
Current=breeze

[Users]
RememberLastUser=true
RememberLastSession=true

[Autologin]
User=
Session=
Relogin=false
